<?xml version="1.0" encoding="utf-8"?><Database Name="user_info" Class="userdbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\user_info.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="Algorithm.Properties.Settings" SettingsPropertyName="user_infoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.person" Member="persons">
    <Type Name="person">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>